// Sanitization boundary for untrusted fence content (```html and ```svg).
//
// WHY: FenceyMD opens arbitrary folders, and a book's markdown is NOT
// necessarily authored by the person reading it — books get shared, downloaded,
// and generated by LLMs. The `html` and `svg` fence renderers insert fence
// bodies into the live DOM via `innerHTML`, which runs inside a Tauri WebView
// that exposes `invoke()` with full IPC authority (write_file, rename_file,
// open_in_external_editor, …). Unsanitized `<script>`, `<img onerror>`,
// `<svg onload>`, `javascript:` URLs, etc. would therefore be a local
// remote-code-execution vector, not just a rendering quirk.
//
// We use DOMPurify (the de-facto standard, continuously fuzzed against bypasses)
// rather than a hand-rolled scrubber — an incomplete allowlist is worse than
// none because it implies safety it doesn't provide. The goal is to keep the
// *visual* feature (render real HTML / SVG) while removing script execution.
import DOMPurify from 'dompurify';

// HTML fence: allow presentational markup + inline styles, strip anything that
// can execute. DOMPurify's defaults already drop <script>, on* handlers, and
// javascript:/data: script URLs; we additionally forbid <iframe>/<object>/
// <embed> (navigable/script-bearing) since a local reader has no need to embed
// remote frames, and that's the most abused "embed" surface.
const HTML_CONFIG = {
  FORBID_TAGS: ['iframe', 'object', 'embed', 'base'],
  // Keep the door shut on event handlers even if a future DOMPurify default
  // changes; ALLOW_* omitted means "use the safe defaults".
};

// SVG fence: use DOMPurify's SVG profiles so shapes/paths/text/filters survive
// but <script>, on* handlers, and <foreignObject>-smuggled HTML do not.
const SVG_CONFIG = { USE_PROFILES: { svg: true, svgFilters: true } };

/**
 * Sanitize an HTML fragment string for insertion via innerHTML.
 *
 * @param {string} dirty - Untrusted HTML; `null`/`undefined` are coerced to ''.
 * @returns {string} HTML with script-execution vectors removed (see HTML_CONFIG).
 */
export function sanitizeHtml(dirty) {
  return DOMPurify.sanitize(dirty ?? '', HTML_CONFIG);
}

/**
 * Sanitize an SVG fragment string (the inner markup of an <svg>).
 *
 * @param {string} dirty - Untrusted SVG markup; `null`/`undefined` -> ''.
 * @returns {string} SVG restricted to the safe shape/path/text/filter profile.
 */
export function sanitizeSvg(dirty) {
  return DOMPurify.sanitize(dirty ?? '', SVG_CONFIG);
}

// Re-export the raw DOMPurify instance for callers needing ad-hoc configs or
// hooks; prefer the named helpers above so the trust-boundary config stays
// centralized rather than re-derived per call site.
export default DOMPurify;
